# Taken from https://github.com/eskatos/gradle-command-action
name: Build IDEA plugin and run tests
on:
  push:
    paths:
      - 'IDEA/**'
  pull_request:
    paths:
      - 'IDEA/**'
jobs:
  gradle:
    # Note: if we wanted, we could expand this to test on multiple OS's
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: test buildPlugin
        build-root-directory: IDEA/
        wrapper-directory: IDEA/
    - uses: actions/upload-artifact@v2
      with:
        name: KerboScript(kOS).zip
        path: IDEA/build/distributions/KerboScript(kOS).zip
